site_name: neusis

nav:
  - Home: index.md
  - Architecture:
    - Architecture: architecture/architecture.md
    - Machine Configurations: architecture/machines.md
  - User Setup:
    - Creating a User: user_setup/create_user.md
    - Adding Users to a Machine: user_setup/add_users.md
    - Customizing Your Home: user_setup/modify_home.md
    - Managing SSH Keys: user_setup/create-keys.md
  - Development:
    - Creating Environments: development/create_env.md
    - Python Environments: development/create-venv.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - admonition

plugins:
  - search
