# supercharged-git: bootstrap-repos module.
# Generates a `gclb-sync` script on PATH that clones every declared
# repo into a single root directory, using `gclb` so each repo lands
# in the bare+worktree layout. Idempotent — repos whose `<dest>/.bare`
# already exists are skipped, so re-running is cheap.
#
# Pair with the umbrella's git setup to bootstrap a fresh dev machine
# in two commands: `home-manager switch` + `gclb-sync`.
{ ... }:
{
  flake.homeModules.supercharged-git-bootstrap-repos =
    {
      config,
      lib,
      pkgs,
      outputs,
      ...
    }:
    let
      cfg = config.neusis.supercharged-git.tools.bootstrap-repos;

      # Normalise each entry to `{ url; dest; }` where `dest = ""`
      # means "derive from the URL inside the shell".
      normalize =
        entry:
        if builtins.isString entry then
          {
            url = entry;
            dest = "";
          }
        else
          {
            inherit (entry) url;
            dest = if entry.dest != null then entry.dest else "";
          };

      cloneCmds = lib.concatMapStringsSep "\n" (
        e: "clone_repo ${lib.escapeShellArg e.url} ${lib.escapeShellArg e.dest} || rc=1"
      ) (map normalize cfg.repos);

      gclbBin = "${outputs.packages.${pkgs.stdenv.hostPlatform.system}.gclb}/bin/gclb";

      gclbSync = pkgs.writeShellApplication {
        name = "gclb-sync";
        runtimeInputs = [ pkgs.git ];
        text = ''
          # Auto-generated by neusis.supercharged-git.tools.bootstrap-repos.
          # Clones the declared repos under LOCATION via gclb,
          # skipping entries whose `<dest>/.bare` already exists.

          LOCATION=${lib.escapeShellArg cfg.location}
          mkdir -p "$LOCATION"
          cd "$LOCATION"

          clone_repo() {
            local url="$1"
            local dest="$2"
            if [[ -z "$dest" ]]; then
              # Same default as gclb itself: last path segment
              # without a `.git` suffix.
              dest=$(basename "''${url%/}" .git)
            fi
            local target="$LOCATION/$dest"
            if [[ -d "$target/.bare" ]]; then
              echo "skip: $dest (already cloned)"
              return 0
            fi
            mkdir -p "$(dirname "$target")"
            echo "==> Cloning $url -> $target"
            ${gclbBin} "$url" -l "$target/.bare"
          }

          rc=0
          ${cloneCmds}

          if [[ "$rc" -ne 0 ]]; then
            echo "warn: one or more clones failed; check output above." >&2
            exit "$rc"
          fi
          echo "Done."
        '';
      };
    in
    {
      options.neusis.supercharged-git.tools.bootstrap-repos = {
        enable = lib.mkEnableOption "declarative repo cloning via `gclb-sync`";

        location = lib.mkOption {
          type = lib.types.str;
          default = "${config.home.homeDirectory}/code";
          defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/code"'';
          example = "/Users/ank/work";
          description = ''
            Absolute path to the root under which `gclb-sync` clones
            repos. Created on first run if missing.
          '';
        };

        repos = lib.mkOption {
          type = lib.types.listOf (
            lib.types.either lib.types.str (
              lib.types.submodule {
                options = {
                  url = lib.mkOption {
                    type = lib.types.str;
                    description = "Git URL to clone (any form `gclb` accepts).";
                  };
                  dest = lib.mkOption {
                    type = lib.types.nullOr lib.types.str;
                    default = null;
                    description = ''
                      Destination directory name under `location`.
                      May contain slashes for nested layouts (e.g.
                      `vendor/lib`). Defaults to the repo name
                      parsed from the URL.
                    '';
                  };
                };
              }
            )
          );
          default = [ ];
          example = lib.literalExpression ''
            [
              "git@github.com:org/dotfiles.git"
              "git@github.com:work/internal-tool.git"
              { url = "https://github.com/upstream/samples.git"; dest = "external/samples"; }
            ]
          '';
          description = ''
            Repos to clone. Each entry is either a bare URL string
            (cloned into `<location>/<repo-name>/.bare/`) or an
            attrset `{ url; dest?; }` for a custom destination
            directory under `location`.
          '';
        };

        autoRun = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = ''
            Run `gclb-sync` automatically on every home-manager
            activation. Off by default — clones are network-dependent
            and slow, so most setups should run `gclb-sync` manually
            after activating a fresh machine. Set true to make
            activation hands-free.
          '';
        };
      };

      config = lib.mkIf cfg.enable (lib.mkMerge [
        {
          home.packages = [ gclbSync ];
        }
        (lib.mkIf cfg.autoRun {
          home.activation.bootstrapRepos = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
            ${gclbSync}/bin/gclb-sync || true
          '';
        })
      ]);
    };
}
