package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/charmbracelet/huh"
	"github.com/leoank/neusis/cli/internal/gen"
	"github.com/leoank/neusis/cli/internal/nix"
	"github.com/leoank/neusis/cli/internal/scaffold"
	"github.com/leoank/neusis/cli/internal/tmpl"
	"github.com/leoank/neusis/cli/internal/wizard"
	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	var (
		name       string
		style      string
		lab        string
		withDarwin bool
		neusisRef  string
		nixpkgsRef string
		hmRef      string
		darwinRef  string
		yes        bool
		force      bool
	)

	cmd := &cobra.Command{
		Use:   "init [dir]",
		Short: "Create a new neusis fleet repository",
		Long: `Scaffold a minimal neusis fleet repository: a flake that imports
neusis as a library plus modules/ holding your machines, users, and
registry labs.

Run with no flags to be guided interactively, or pass flags (with
--yes) to script it.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			target := "."
			if len(args) == 1 {
				target = args[0]
			}
			absTarget, err := filepath.Abs(target)
			if err != nil {
				return err
			}
			if name == "" {
				name = filepath.Base(absTarget)
			}
			if style == "" {
				style = wizard.DefaultStyle
			}
			if lab == "" {
				lab = wizard.DefaultLab
			}

			repo := tmpl.Repo{
				Name:          name,
				Style:         style,
				NeusisRef:     neusisRef,
				NixpkgsRef:    nixpkgsRef,
				HMRef:         hmRef,
				DarwinRef:     darwinRef,
				IncludeDarwin: withDarwin,
			}

			var addMachine, addUser bool
			interactive := !yes && isTTY()
			if interactive {
				if err := runInitForm(&repo, &lab, &addMachine, &addUser); err != nil {
					return err
				}
			}

			if err := os.MkdirAll(absTarget, 0o755); err != nil {
				return err
			}
			w := scaffold.New(absTarget)
			w.Force = force

			if err := gen.Repo(w, repo); err != nil {
				return err
			}
			if err := gen.Lab(w, tmpl.Lab{Name: lab}); err != nil {
				return err
			}

			if addMachine {
				m := tmpl.Machine{Lab: lab, StateVersion: wizard.DefaultStateVersion}
				if err := runMachineForm(&m); err != nil {
					return err
				}
				if err := gen.Machine(w, m); err != nil {
					return err
				}
			}
			if addUser {
				u := tmpl.User{Lab: lab, Shell: "zsh", Role: "admin"}
				if err := runUserForm(w, &u); err != nil {
					return err
				}
				if err := gen.User(w, u); err != nil {
					return err
				}
			}

			out := cmd.OutOrStdout()
			fmt.Fprintf(out, "Scaffolded %s (%s style) in %s:\n", name, repo.Style, absTarget)
			reportWritten(out, w)

			ctx := cmd.Context()
			_ = nix.GitInit(ctx, absTarget)
			if nix.IsRepo(absTarget) {
				_ = nix.GitAdd(ctx, absTarget, w.Written()...)
			}

			printInitNextSteps(cmd, absTarget, repo, interactive)
			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&name, "name", "", "project/flake name (default: target dir name)")
	f.StringVar(&style, "style", "", "flake style: dendritic (default) or plain")
	f.StringVar(&lab, "lab", "", "name of the first registry lab (default: home)")
	f.BoolVar(&withDarwin, "darwin", false, "include the nix-darwin input (for macOS hosts)")
	f.StringVar(&neusisRef, "neusis-ref", wizard.DefaultNeusisRef, "flake ref for the neusis library")
	f.StringVar(&nixpkgsRef, "nixpkgs-ref", wizard.DefaultNixpkgsRef, "flake ref for nixpkgs")
	f.StringVar(&hmRef, "hm-ref", wizard.DefaultHMRef, "flake ref for home-manager")
	f.StringVar(&darwinRef, "darwin-ref", wizard.DefaultDarwinRef, "flake ref for nix-darwin")
	f.BoolVar(&yes, "yes", false, "non-interactive: use flags and defaults, skip prompts")
	f.BoolVar(&force, "force", false, "overwrite existing files")
	return cmd
}

func runInitForm(repo *tmpl.Repo, lab *string, addMachine, addUser *bool) error {
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Project name").
				Description("Used as the flake description.").
				Value(&repo.Name).
				Validate(wizard.ValidateNonEmpty),
			huh.NewSelect[string]().
				Title("Flake style").
				Description("dendritic mirrors neusis (flake.nix generated by write-flake).\nplain is a static hand-written flake.nix, buildable without nix.").
				Options(
					huh.NewOption("dendritic (recommended)", "dendritic"),
					huh.NewOption("plain", "plain"),
				).
				Value(&repo.Style),
			huh.NewInput().
				Title("First lab name").
				Description("A lab groups machines and users (e.g. home, work, cslab).").
				Value(lab).
				Validate(wizard.ValidateIdent),
			huh.NewConfirm().
				Title("Include the nix-darwin input?").
				Description("Enable if any host runs macOS.").
				Value(&repo.IncludeDarwin),
		),
		huh.NewGroup(
			huh.NewConfirm().
				Title("Add a machine now?").
				Value(addMachine),
			huh.NewConfirm().
				Title("Add a user now?").
				Value(addUser),
		),
	)
	return form.Run()
}

func printInitNextSteps(cmd *cobra.Command, dir string, repo tmpl.Repo, interactive bool) {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "\nNext steps:")
	rel, _ := filepath.Rel(mustCwd(), dir)
	if rel != "." && rel != "" {
		fmt.Fprintf(out, "  cd %s\n", rel)
	}
	fmt.Fprintln(out, "  neusis add machine      # add a host")
	fmt.Fprintln(out, "  neusis add user         # add a person")

	if !nix.HasNix() {
		fmt.Fprintln(out, "\nInstall nix, then run `nix flake lock` to pin inputs.")
		return
	}
	if repo.Style == "dendritic" {
		fmt.Fprintln(out, "\nTo pin inputs and (re)generate flake.nix:")
		fmt.Fprintln(out, "  git add . && nix run .#write-flake && nix flake lock")
	} else {
		fmt.Fprintln(out, "\nTo pin inputs:")
		fmt.Fprintln(out, "  nix flake lock")
	}
}

func mustCwd() string {
	d, err := os.Getwd()
	if err != nil {
		return ""
	}
	return d
}
