{ ... }:
{
  imports = [
    # In a real config, this would be the file generated by
    # `nixos-generate-config` for this host.
    # (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # mkNeusisOS does not pin a system, so the consumer must.
  nixpkgs.hostPlatform = "x86_64-linux";

  networking.hostName = "myhost";

  # Stand-in for real bootloader/filesystem configuration.
  boot.loader.systemd-boot.enable = true;
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  services.openssh.enable = true;

  system.stateVersion = "25.11";
}
